JAVAC =javac
JAVAC_FLAGS =

all:	Mylib.class ListNode.class OperateListNode.class TreeNode.class Codec.class OperateTreeNode.class Solution.class Main.class

Mylib.class:	Mylib.java
	$(JAVAC) $(JAVAC_FLAGS) $<

ListNode.class:	ListNode.java
	$(JAVAC) $(JAVAC_FLAGS) $<

OperateListNode.class:	OperateListNode.java
	$(JAVAC) $(JAVAC_FLAGS) $<

TreeNode.class:	TreeNode.java
	$(JAVAC) $(JAVAC_FLAGS) $<

Codec.class:	Codec.java
	$(JAVAC) $(JAVAC_FLAGS) $<

OperateTreeNode.class:	OperateTreeNode.java
	$(JAVAC) $(JAVAC_FLAGS) $<

Solution.class:	Solution.java
	$(JAVAC) $(JAVAC_FLAGS) $<

Main.class:	Main.java
	$(JAVAC) $(JAVAC_FLAGS) $<

clean:
	rm ./*.class

.PHONY:	all clean
